import type { Metadata } from "next";
import "../styles/globals.css";

export const metadata: Metadata = {
  title: "My Next.js App",
  description: "Generated by create next app",
  keywords: "next.js, zustand, tailwind",
  robots: "index, follow",
  openGraph: {
    title: "My Next.js App",
    description: "Generated by create next app",
    url: "https://example.com",
    siteName: "My Next.js App",
    images: [
      {
        url: "/og-image.png", // 프로젝트 내 public 폴더에 이미지 위치
        width: 1200,
        height: 630,
        alt: "My Next.js App",
      },
    ],
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "My Next.js App",
    description: "Generated by create next app",
    images: ["/og-image.png"],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
